### ISSUE TITLE
how to install 

### ISSUE THREAD

**Issue by wangshifeng** [varunsharma27/navigation#1]
hi,how to install this plugin?

**Comment by jartigag** [comment]
same here! :grin:
trying:
```
$ wget https://github.com/varunsharma27/navigation/archive/master.zip -O navigation-varunsharma27.zip
$ cd /usr/share/kibana
$ sudo bin/kibana-plugin install file:///home/myUser/navigation-varunsharma27.zip
```
but `Plugin installation was unsuccessful due to error "No kibana plugins found in archive"`

neither `$ sudo bin/kibana-plugin install navigation` nor `$ sudo bin/kibana-plugin install https://artifacts.elastic.co/downloads/kibana-plugins/navigation/navigation-6.5.4.zip` worked..

**Comment by varunsharma27** [comment]
Try this package :- https://github.com/varunsharma27/navigation/blob/master/build/navigation-1.0.0.zip
This is a build for 6.5.4
You may also create your own custom build (With any 6.x Kibana version), details in [README.md](https://github.com/varunsharma27/navigation/blob/master/README.md)

**Comment by jartigag** [comment]
i've followed the steps to build it for 6.6.0, but..
```
ERROR in ./plugins/navigation/public/navigation.js
    Module not found: Error: Can't resolve 'ui/vis/vis_category' in '/usr/share/kibana/plugins/navigation/public'
```

it seems to be the same problem as https://github.com/dlumbrer/kbn_network/issues/67 (as recent as yesterday!)

**Comment by varunsharma27** [comment]
@jartigag It appears that kibana has had a refactor in 6.6.0. This plugin is confirmed to work till 6.5.4, I'll create a new release for 6.6.0
Issue created #4
